services:
  - type: web
    name: phalmitra-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: MODEL_PATH
        value: model.h5
    autoDeploy: true
